import Head from "next/head";
import Link from "next/link";

const defaultEndPoint = `https://rickandmortyapi.com/api/character/`;
export async function getServerSideProps({ query }) {
  const { id } = query;
  const res = await fetch(`${defaultEndPoint}+${id}`);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default function Character({ data }) {
  console.log("data", data);

  const { id, name, status, species, type, gender, image, location, origin } =
    data;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{name}</h1>

        <p>
          Details {status} {species} {gender}
        </p>

        <img src={image} />

        <p>
          <Link data-testid="back" href="/">Back to all characters</Link>
        </p>
      </main>
    </div>
  );
}
